ekf_filter_node:
  ros__parameters:
    # how often the filter should run (Hz)
    frequency: 30.0
    # how long until an input is considered stale (s)
    sensor_timeout: 0.1
    two_d_mode: true

    # frames
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # Input 0: IMU
    # imu0: /imu/data
    # imu0_config: [false, false, false,
    #                true,  true,  true,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false]
    # imu0_queue_size: 10

    # Input 1: raw odom
    odom0: /scout/odom
    odom0_config: [ 
      false, false, false,   # x, y, z positions
      false, false, false,   # roll, pitch, yaw
      true,  true,  false,   # vx, vy, vz   ← enable both vx & vy!
      false, false, true,    # vroll, vpitch, vyaw
      false, false, false    # ax, ay, az
    ]
    odom0_queue_size: 10

    # output TF + topics
    publish_tf: true
    publish_acceleration: false
